$type: DataViewPage
props:
  title:
    $map: '`${params.namespace} - Deployments`'
  url:
    $map: |
      `${config.host}/apis/extensions/v1beta1/namespaces/${params.namespace}/deployments`
  headers:
    $map: config.headers
  root: items
  mapper:
    $mapper: |-
      props.map((ds)=>{
        const md = ds.metadata;
        return {
          baseLink: params.env?`/kubernetes/${params.env}`:'/kubernetes',
          name: md.name,
          namespace: md.namespace,
          created: md.creationTimestamp,
          labels: md.labels
        };
      })
  suppress:
    - baseLink
  actions:
    - link:
        $mapper: >-
          `${props.baseLink}/namespace/${params.namespace}/deployment/${props.name}${extractQueryParams(['apiBase'])}`
      caption: Details
      btnStyle: primary
    - delete:
        $mapper: |
          `${config.host}/apis/extensions/v1beta1/namespaces/${params.namespace}/deployments/${props.name}`
      caption: Delete
      message: 'Are you sure you want to delete ${name}?'
      headers:
        $map: config.headers
paths:
  - /kubernetes/namespace/:namespace/deployments
  - /kubernetes/:env/namespace/:namespace/deployments
