$type: DataViewPage
props:
  title:
    $map: '`${params.namespace} - ${params.name}`'
  url:
    $map: |
      `${config.host}/apis/extensions/v1beta1/namespaces/${params.namespace}/deployments/${params.name}`
  headers:
    $map: config.headers
paths:
  - /kubernetes/namespace/:namespace/deployment/:name
  - /kubernetes/:env/namespace/:namespace/deployment/:name
