$type: DataViewPage
props:
  title:
    $map: '`${params.namespace} - ${params.name}`'
  url:
    $map: >-
      (params.env?`/api/${params.env}/kube`:"/api/kube")+`/apis/extensions/v1beta1/namespaces/${params.namespace}/ingresses/${params.name}`
paths:
  - /kubernetes/namespace/:namespace/ingress/:name
  - /kubernetes/:env/namespace/:namespace/ingress/:name
