$type: HeaderPage
props:
  title:
    $map: '`${params.namespace} - Services`'
children:
  $type: Panel
  children:
    $type: Provider
    props:
      provide:
        data:
          url:
            $map: >-
              (params.env?`/api/${params.env}/kube`:"/api/kube")+`/api/v1/namespaces/${params.namespace}/services`
          root: items
          mapper:
            $mapper: |-
              props.map((pod)=>{
                return {
                  baseLink: params.env?`/kubernetes/${params.env}`:'/kubernetes',
                  name: getObjectValue('metadata.name', pod),
                  namespace: getObjectValue('metadata.namespace', pod),
                  created: getObjectValue('metadata.creationTimestamp', pod)
                };
              })
      Component:
        $component: ActionTable
      props:
        suppress:
          - baseLink
        actions:
          - link:
              $mapper: >-
                `${props.baseLink}/namespace/${params.namespace}/service/${props.name}${extractQueryParams(['apiBase'])}`
            caption: Details
            btnStyle: primary
paths:
  - /kubernetes/namespace/:namespace/services
  - /kubernetes/:env/namespace/:namespace/services
