$type: DataViewPage
props:
  title:
    $map: '`${params.namespace} - ${params.name}`'
  url:
    $map: |
      `${config.host}/api/v1/namespaces/${params.namespace}/services/${params.name}`
paths:
  - /kubernetes/namespace/:namespace/service/:name
  - /kubernetes/:env/namespace/:namespace/service/:name
